DOMAIN = "kodi_media_sensors"
CONF_LABEL = "label"
CONF_KODI_ENTITY = "kodi_entity_id"

# Kodi service (core integration) used to call JSON-RPC methods
KODI_DOMAIN = "kodi"
SERVICE_CALL_METHOD = "call_method"

# Default Kodi playlist (0 = audio playlist, see Playlist.GetPlaylists)
DEFAULT_PLAYLIST_ID = 0

KODI_STATE_IDLE = "idle"
KODI_STATE_ON = "on"
KODI_STATE_OFF = "off"
KODI_STATE_PAUSE = "pause"
KODI_STATE_UNAVAILABLE = "unavailable"
KODI_STATES = {
    KODI_STATE_IDLE,
    KODI_STATE_OFF,
    KODI_STATE_ON,
    KODI_STATE_PAUSE,
    KODI_STATE_UNAVAILABLE,
}

MAX_SEARCH_LIMIT = 100

OPTION_HIDE_WATCHED = "hide_watched"
OPTION_SEARCH_SONGS_LIMIT = "search_songs_limit"
OPTION_SEARCH_ARTISTS_LIMIT = "search_artists_limit"
OPTION_SEARCH_ALBUMS_LIMIT = "search_albums_limit"
OPTION_SEARCH_MUSICVIDEOS_LIMIT = "search_musicvideos_limit"
OPTION_SEARCH_MOVIES_LIMIT = "search_movies_limit"
OPTION_SEARCH_TVSHOWS_LIMIT = "search_tvshows_limit"
OPTION_SEARCH_CHANNELS_TV_LIMIT = "search_channels_tv_limit"
OPTION_SEARCH_CHANNELS_RADIO_LIMIT = "search_channels_radio_limit"
OPTION_SEARCH_EPISODES_LIMIT = "search_episodes_limit"
OPTION_SEARCH_MUSIC_PLAYLISTS_LIMIT = "search_music_playlists_limit"
OPTION_SEARCH_RECENTLY_ADDED_SONGS_LIMIT = "search_recently_added_songs_limit"
OPTION_SEARCH_RECENTLY_ADDED_ALBUMS_LIMIT = "search_recently_added_albums_limit"
OPTION_SEARCH_RECENTLY_ADDED_MOVIES_LIMIT = "search_recently_added_movies_limit"
OPTION_SEARCH_RECENTLY_ADDED_MUSICVIDEOS_LIMIT = (
    "search_recently_added_musicvideos_limit"
)
OPTION_SEARCH_RECENTLY_ADDED_EPISODES_LIMIT = "search_recently_added_episodes_limit"
OPTION_SEARCH_RECENTLY_PLAYED_SONGS_LIMIT = "search_recently_played_songs_limit"
OPTION_SEARCH_RECENTLY_PLAYED_ALBUMS_LIMIT = "search_recently_played_albums_limit"


DEFAULT_OPTION_HIDE_WATCHED = False
DEFAULT_OPTION_SEARCH_SONGS_LIMIT = 15
DEFAULT_OPTION_SEARCH_ARTISTS_LIMIT = 10
DEFAULT_OPTION_SEARCH_ALBUMS_LIMIT = 10
DEFAULT_OPTION_SEARCH_MOVIES_LIMIT = 5
DEFAULT_OPTION_SEARCH_MUSICVIDEOS_LIMIT = 10
DEFAULT_OPTION_SEARCH_TVSHOWS_LIMIT = 5
DEFAULT_OPTION_SEARCH_EPISODES_LIMIT = 5
DEFAULT_OPTION_SEARCH_CHANNELS_TV_LIMIT = 10
DEFAULT_OPTION_SEARCH_CHANNELS_RADIO_LIMIT = 5
DEFAULT_OPTION_SEARCH_MUSIC_PLAYLISTS_LIMIT = 10

DEFAULT_OPTION_SEARCH_RECENTLY_ADDED_SONGS_LIMIT = 20
DEFAULT_OPTION_SEARCH_RECENTLY_ADDED_ALBUMS_LIMIT = 20
DEFAULT_OPTION_SEARCH_RECENTLY_ADDED_MOVIES_LIMIT = 20
DEFAULT_OPTION_SEARCH_RECENTLY_ADDED_EPISODES_LIMIT = 20
DEFAULT_OPTION_SEARCH_RECENTLY_ADDED_MUSICVIDEOS_LIMIT = 20

DEFAULT_OPTION_SEARCH_RECENTLY_PLAYED_SONGS_LIMIT = 10
DEFAULT_OPTION_SEARCH_RECENTLY_PLAYED_ALBUMS_LIMIT = 10

