services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.7.2
    container_name: ha_dev
    network_mode: host
    volumes:
      # Allow VS Code to open the project without path errors
      - ..:/workspaces/kodi-media-sensors:cached
      # Store the local Home Assistant configuration
      - ../config:/config
      # Mount the integration where Home Assistant expects it
      - ../custom_components:/config/custom_components
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["hass", "-c", "/config"]