name: Push changes

on:
  push:
    branches:
      - main
      - develop

jobs:
  validate_hacs:
    name: Validate HACS requirements
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
  
  validate_hassfest:
    name: Validate with Hassfest for Home assistant
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master

